version: "3"
services:

  models:
    image: tp33/django
    volumes:
      - ~/dev/deploy/Dogploy:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory  ~/dev/deploy/Dogploy --reload-on-changes ~/dev/deploy/Dogploy/wsgi.py"

networks:
  backend:
