version: "3"
services:

  models:
    image: tp33/django
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    networks:
      - backend
    command: bash -c "mod_wsgi-express start-server --working-directory  app/dogploy --reload-on-changes app/dogploy/dogploy/wsgi.py"

networks:
  backend:
